# Default values for modelserverchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# data.zip location
data:
  datadirectory: http://s3-eu-west-1.amazonaws.com/fdp-killrweather-data/data/data.zip
# docker images
image:
  akka: lightbend/fdp-akka-kafka-streams-model-server-akka-streams-server
  kafka: lightbend/fdp-akka-kafka-streams-model-server-kafka-streams-server
  publisher: lightbend/fdp-akka-kafka-streams-model-server-model-publisher
  pullPolicy: Always
  version: 1.2.0
# Configuration parameters for an application
configuration:
  kafka:
    brokerlist : "broker.kafka.l4lb.thisdcos.directory:9092"
  grafana :
    host : grafana.marathon.l4lb.thisdcos.directory
    port : 3000
  influx :
    host : influxdb.marathon.l4lb.thisdcos.directory
    port : 8086
  statelistener :
    port : 5500
  publisher :
    data_publish_interval : 1 second
    model_publish_interval : 5 minutes
    data_mount : /usr/share
    data_file : winequality_red.csv
# Server type. If akka - install akka implementation, otherwise - kafka implementation
server:
  type: akka