# Default values for transformchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# data.zip location
data:
  datadirectory: http://fdp-sample-apps-artifacts.s3.amazonaws.com/clarknet_access_log_Aug28.tgz

# docker images
image:
  repository: lightbend
  name: fdp-kstream-dsl
  tag: 1.2.1
  pullPolicy: Always
  version: 1.2.1

# Configuration parameters for an application
configuration:
  kafka:
    brokerlist : broker.kafka.l4lb.thisdcos.directory:9092
  rest:
    interface : "0.0.0.0"
  schemaregistry:
    url : ""
