apiVersion: v1
kind: Pod
metadata:
  name: kstreamprocchart
  labels:
    app: kstreamproc
spec:
  containers:
  - name: kstreamproctransformer
    image: {{ .Values.image.proc}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - name: http
      containerPort: {{ .Values.configuration.statelistenerPROCEDURE.port}}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
    env:          
    - name: "DIRECTORY_TO_WATCH"
      value: "/usr/share"
    - name: "KAFKA_BROKERS"
      value: {{ .Values.configuration.kafka.brokerlist}}
    - name: "INTERFACE_PROC"
      value: {{ .Values.configuration.rest.interface}}
    - name: "PORT0"
      value: "{{ .Values.configuration.statelistenerPROCEDURE.port}}"
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectoryproc }} -O /data-dir/clarknet_access_log_Sep4.tgz; tar xvfz /data-dir/clarknet_access_log_Sep4.tgz -C /data-dir
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kstreamproc
spec:
  selector:
    app: kstreamproc
  ports:
  - protocol: TCP
    port: {{ .Values.configuration.statelistenerPROCEDURE.port}}
    targetPort: {{ .Values.configuration.statelistenerPROCEDURE.port}}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class}}
    traefik.frontend.rule.type: PathPrefixStrip
  name: kstreamproc
spec:
  rules:
  - http:
      paths:
      - path: /kstreamproc
        backend:
          serviceName: kstreamproc
          servicePort: {{ .Values.configuration.statelistenerPROCEDURE.port}}

