apiVersion: v1
kind: Pod
metadata:
  name: kstreamdslchart
spec:
  hostNetwork: true
  containers:
  - name: kstreamdsltransformer
    image: {{ .Values.image.dsl}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
    env:          
    - name: "DIRECTORY_TO_WATCH"
      value: "/usr/share"
    - name: "KAFKA_BROKERS"
      value: {{ .Values.configuration.kafka.brokerlist}}
    - name: "INTERFACE_DSL"
      value: {{ .Values.configuration.rest.interface}}
    - name: "SCHEMA_REGISTRY_URL"
      value: {{ .Values.configuration.schemaregistry.url}}
  # These container runs during pod initialization
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectorydsl }} -O /data-dir/clarknet_access_log_Aug28.tgz; tar xvfz /data-dir/clarknet_access_log_Aug28.tgz -C /data-dir
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}

