apiVersion: v1
kind: Pod
metadata:
  name: kstreamdslchart
  labels:
    app: kstreamdsl
spec:
  containers:
  - name: kstreamdsltransformer
    image: {{ .Values.image.dsl}}:{{.Values.image.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
    - name: http
      containerPort: {{ .Values.configuration.statelistenerDSL.port}}
    volumeMounts:
    - name: datadir
      mountPath: /usr/share
    env:          
    - name: "DIRECTORY_TO_WATCH"
      value: "/usr/share"
    - name: "KAFKA_BROKERS"
      value: {{ .Values.configuration.kafka.brokerlist}}
    - name: "INTERFACE_DSL"
      value: {{ .Values.configuration.rest.interface}}
    - name: "SCHEMA_REGISTRY_URL"
      value: {{ .Values.configuration.schemaregistry.url}}
    - name: "PORT0"
      value: "{{ .Values.configuration.statelistenerDSL.port}}"
      
  initContainers:
  - name: install
    image: busybox
    command:
    - sh
    - -c
    - wget {{ .Values.data.datadirectorydsl }} -O /data-dir/clarknet_access_log_Aug28.tgz; tar xvfz /data-dir/clarknet_access_log_Aug28.tgz -C /data-dir
    volumeMounts:
    - name: datadir
      mountPath: "/data-dir"
  dnsPolicy: Default
  volumes:
  - name: datadir
    emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kstreamdsl
spec:
  selector:
    app: kstreamdsl
  ports:
  - protocol: TCP
    port: {{ .Values.configuration.statelistenerDSL.port}}
    targetPort: {{ .Values.configuration.statelistenerDSL.port}}

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class}}
    traefik.frontend.rule.type: PathPrefixStrip
  name: kstreamdsl
spec:
  rules:
  - http:
      paths:
      - path: /kstreamdsl
        backend:
          serviceName: kstreamdsl
          servicePort: {{ .Values.configuration.statelistenerDSL.port}}
